<a href="https://colab.research.google.com/github/Pitiki10/TP-GRUPAL---SuperStore/blob/main/Trabajo_Practico_3.4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**3.1. Carga y exploración inicial**

In [16]:
# Importación de librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sympy as sp
from scipy.optimize import curve_fit

# Configuración opcional para mejorar la visualización de números flotantes
pd.set_option("display.float_format", lambda x: "%.2f" % x)

# Carga del dataset
url_dataset = "https://raw.githubusercontent.com/Pitiki10/TP-GRUPAL---SuperStore/main/data/superstore.csv"
df = pd.read_csv(url_dataset, encoding="latin1")

# Impresión estructurada de metadatos y estadísticas
print("======================================================================")
print("I. ESTRUCTURA Y TIPOS DE DATOS DEL DATASET (Método .info())")
print("======================================================================")
df.info()

print("\n" + "-"*70 + "\n") # Guiones medios para separar ambos métodos

# Impresión estructurada de medidas en variables numericas
print("======================================================================")
print("II. ESTADÍSTICA DESCRIPTIVA DE VARIABLES NUMÉRICAS (Método .describe())")
print("======================================================================")
print(df.describe())
print("======================================================================")

======================================================================
I. ESTRUCTURA Y TIPOS DE DATOS DEL DATASET (Método .info())
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

----------------------------------------------------------------------

======================================================================
II. ESTADÍSTICA DESCRIPTIVA DE VARIABLES NUMÉRICAS (Método .describe())
======================================================================
       Row ID  Postal Code    Sales  Quantity  Discount   Profit
count 9994.00      9994.00  9994.00   9994.00   9994.00  9994.00
mean  4997.50     55190.38   229.86      3.79      0.16    28.66
std   2885.16     32063.69   623.25      2.23      0.21   234.26
min      1.00      1040.00     0.44      1.00      0.00 -6599.98
25%   2499.25     23223.00    17.28      2.00      0.00     1.73
50%   4997.50     56430.50    54.49      3.00      0.20     8.67
75%   7495.75     90008.00   209.94      5.00      0.20    29.36
max   9994.00     99301.00 22638.48     14.00      0.80  8399.98
======================================================================



---

# **3.2. Pregunta de investigación**

## ¿Existe un nivel de descuento a partir del cual el incremento en las ventas deja de compensar la reducción del margen de ganancia, provocando una disminución significativa de la rentabilidad de la empresa?

## b) ¿Por qué vale la pena responderla?

Los descuentos son una de las herramientas comerciales más utilizadas para aumentar las ventas y atraer clientes. Sin embargo, una estrategia de descuentos excesivos puede generar un aumento en el volumen vendido sin traducirse en mayores beneficios económicos. Comprender la relación entre descuento y rentabilidad permite identificar prácticas comerciales eficientes, detectar niveles de descuento potencialmente perjudiciales y contribuir a una mejor toma de decisiones en materia de precios y promociones.

Además, este análisis permite determinar si existen categorías de productos, segmentos de clientes o regiones donde los descuentos tienen un impacto diferente sobre la ganancia, aportando información relevante para optimizar la estrategia comercial de la empresa.

## c) ¿Qué respuesta encontramos?

A través del análisis y las visualizaciones desarrolladas, encontramos una respuesta para nuestra pregunta de investigación: sí, existe un límite crítico, y está fijado exactamente en el 20% de descuento (proporción de 0.2). Los datos demuestran que las políticas de rebajas leves (rango bajo, del 0% al 10%) funcionan de manera eficiente, optimizando la ganancia promedio e incluso superando el rendimiento de las operaciones que se venden a precio de lista sin ningún beneficio. Sin embargo, una vez que se cruza el umbral del 20%, la estrategia comercial entra en una zona de rendimientos decrecientes. Pasado este punto de quiebre, el incremento en el volumen de ventas no logra compensar la caída del margen unitario.

La rentabilidad se desploma y la gran mayoría de las transacciones caen por debajo de la línea de equilibrio, generando pérdidas operativas para la organización en lugar de beneficios. También descubrimos que el impacto no es igual en toda la empresa: la sensibilidad varía según las categorías de productos, siendo algunos sectores mucho más vulnerables a quedar en números bajos que otros ante promociones notables. En conclusión, los descuentos excesivos no arman valor por volumen, sino que rompen financieramente el negocio.



---

#**3.3. Transformaciones y resumen estadístico**

## Transformación 1: Creación de rangos de descuento

Con el objetivo de facilitar el análisis de la relación entre descuentos y rentabilidad, se creó una nueva variable denominada **Rango_Descuento**.

La variable original **Discount** contiene valores numéricos continuos, lo que dificulta la comparación entre grupos. Por este motivo, los descuentos fueron agrupados en categorías: *Sin descuento*, *Bajo*, *Medio*, *Alto* y *Muy alto*.

Esta transformación permite comparar de manera más clara indicadores como ventas, ganancias y margen de rentabilidad entre distintos niveles de descuento, facilitando la identificación de posibles umbrales a partir de los cuales los descuentos dejan de ser rentables.

Posteriormente, esta nueva variable será utilizada para construir tablas resumen, gráficos comparativos y analizar si existe una relación entre el nivel de descuento aplicado y la rentabilidad obtenida.

In [17]:
# Definición de los intervalos de descuento
bins = [-0.01, 0, 0.10, 0.20, 0.40, 1.00]

# Etiquetas para cada rango
labels = [
    "Sin descuento",
    "Bajo (0%-10%)",
    "Medio (10%-20%)",
    "Alto (20%-40%)",
    "Muy alto (>40%)"
]

# Creación de la nueva variable categórica
df["Rango_Descuento"] = pd.cut(
    df["Discount"],
    bins=bins,
    labels=labels
)

# Verificación de la transformación
print(df[["Discount", "Rango_Descuento"]].head())
print()
# Cantidad de registros por categoría
print(df["Rango_Descuento"].value_counts().sort_index())

   Discount  Rango_Descuento
0      0.00    Sin descuento
1      0.00    Sin descuento
2      0.00    Sin descuento
3      0.45  Muy alto (>40%)
4      0.20  Medio (10%-20%)

Rango_Descuento
Sin descuento      4798
Bajo (0%-10%)        94
Medio (10%-20%)    3709
Alto (20%-40%)      460
Muy alto (>40%)     933
Name: count, dtype: int64

## Transformación 2: Creación de una variable de margen de rentabilidad

Con el objetivo de evaluar el impacto de los descuentos sobre la rentabilidad, se creó una nueva variable denominada **Margen_Rentabilidad**.

La variable **Profit** indica la ganancia o pérdida obtenida en cada venta, pero no permite comparar directamente operaciones de diferente tamaño. Por ejemplo, una ganancia de 100 dólares puede ser muy buena en una venta de 500 dólares y poco significativa en una venta de 10.000 dólares.

Por este motivo, se calculó el margen de rentabilidad como la proporción de ganancia respecto de las ventas realizadas. Esta medida permite comparar de manera más adecuada la eficiencia económica de distintas operaciones, independientemente de su volumen de ventas.

La nueva variable será utilizada para analizar si los descuentos más elevados reducen la rentabilidad relativa de las ventas y para identificar posibles niveles de descuento asociados con márgenes bajos o negativos.

In [18]:
# Margen de rentabilidad expresado como porcentaje
# Fórmula: ganancia / ventas

df["Margen_Rentabilidad_Porc"] = (
    df["Profit"] / df["Sales"]
) * 100

print(
    df[
        [
            "Sales",
            "Profit",
            "Margen_Rentabilidad_Porc"
        ]
    ].head()
)
print()
# Estadísticas descriptivas de la nueva variable
print(df["Margen_Rentabilidad_Porc"].describe())

   Sales  Profit  Margen_Rentabilidad_Porc
0 261.96   41.91                     16.00
1 731.94  219.58                     30.00
2  14.62    6.87                     47.00
3 957.58 -383.03                    -40.00
4  22.37    2.52                     11.25

count   9994.00
mean      12.03
std       46.68
min     -275.00
25%        7.50
50%       27.00
75%       36.25
max       50.00
Name: Margen_Rentabilidad_Porc, dtype: float64

## Transformación 3: Identificación de ventas con pérdida

Con el objetivo de analizar el impacto de los descuentos sobre los resultados económicos de cada operación, se creó una nueva variable denominada **Resultado_Venta**.

La variable **Profit** indica la ganancia o pérdida obtenida en cada transacción. Sin embargo, para ciertos análisis resulta más útil clasificar las operaciones según si fueron rentables o no, en lugar de observar únicamente el valor numérico de la ganancia.

Por este motivo, se creó una variable categórica que identifica cada venta como **Rentable** cuando la ganancia es positiva o nula, y **Con pérdida** cuando la ganancia es negativa.

Esta transformación permitirá calcular la proporción de operaciones con pérdidas en cada rango de descuento y evaluar si los descuentos más elevados aumentan la frecuencia de ventas no rentables.

In [19]:
# Creación de una variable que clasifica cada venta
# según el resultado económico obtenido

df["Resultado_Venta"] = df["Profit"].apply(
    lambda x: "Con pérdida" if x < 0 else "Rentable"
)

# Verificación de la nueva variable
print(df[["Profit", "Resultado_Venta"]].head())
print()
# Cantidad de operaciones en cada categoría
print(df["Resultado_Venta"].value_counts())

   Profit Resultado_Venta
0   41.91        Rentable
1  219.58        Rentable
2    6.87        Rentable
3 -383.03     Con pérdida
4    2.52        Rentable

Resultado_Venta
Rentable       8123
Con pérdida    1871
Name: count, dtype: int64

## Estadístico de resumen 1: Profit promedio por categoría y rango de descuento

Con el objetivo de analizar si el impacto de los descuentos varía según el tipo de producto, se calculó la ganancia promedio (**Profit**) para cada combinación de categoría de producto y rango de descuento.

Mientras que el análisis general permite observar la relación entre descuentos y rentabilidad en todo el dataset, este agrupamiento permite identificar si algunas categorías son más sensibles a los descuentos que otras.

El cálculo de la ganancia promedio por grupo facilita la comparación entre categorías y permite detectar situaciones donde determinados niveles de descuento podrían generar una reducción significativa de la rentabilidad o incluso pérdidas.

Este análisis resulta relevante para la pregunta de investigación, ya que ayuda a determinar si existe un nivel de descuento que afecta negativamente la rentabilidad y si dicho efecto se presenta de manera uniforme en todas las categorías.

In [20]:
# Profit promedio por categoría y rango de descuento

profit_promedio_categoria = (
    df.groupby(
        ["Category", "Rango_Descuento"]
    )["Profit"]
    .mean()
    .round(2)
    .reset_index()
)

# Mostrar resultados
print(profit_promedio_categoria)

# Ordenar para facilitar la lectura
profit_promedio_categoria = profit_promedio_categoria.sort_values(
    by=["Category", "Rango_Descuento"]
)

profit_promedio_categoria.head(15)

           Category  Rango_Descuento  Profit
0         Furniture    Sin descuento   69.54
1         Furniture    Bajo (0%-10%)   93.57
2         Furniture  Medio (10%-20%)   11.52
3         Furniture   Alto (20%-40%)  -90.35
4         Furniture  Muy alto (>40%) -115.61
5   Office Supplies    Sin descuento   41.71
6   Office Supplies    Bajo (0%-10%)   67.88
7   Office Supplies  Medio (10%-20%)   17.28
8   Office Supplies   Alto (20%-40%)     NaN
9   Office Supplies  Muy alto (>40%)  -69.32
10       Technology    Sin descuento  158.88
11       Technology    Bajo (0%-10%)  416.04
12       Technology  Medio (10%-20%)   54.74
13       Technology   Alto (20%-40%)  -48.11
14       Technology  Muy alto (>40%) -777.56

/tmp/ipykernel_16727/3521918464.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(

           Category  Rango_Descuento  Profit
0         Furniture    Sin descuento   69.54
1         Furniture    Bajo (0%-10%)   93.57
2         Furniture  Medio (10%-20%)   11.52
3         Furniture   Alto (20%-40%)  -90.35
4         Furniture  Muy alto (>40%) -115.61
5   Office Supplies    Sin descuento   41.71
6   Office Supplies    Bajo (0%-10%)   67.88
7   Office Supplies  Medio (10%-20%)   17.28
8   Office Supplies   Alto (20%-40%)     NaN
9   Office Supplies  Muy alto (>40%)  -69.32
10       Technology    Sin descuento  158.88
11       Technology    Bajo (0%-10%)  416.04
12       Technology  Medio (10%-20%)   54.74
13       Technology   Alto (20%-40%)  -48.11
14       Technology  Muy alto (>40%) -777.56

**Interpretación**: Con esta tabla podemos observar la ganancia promedio de cada sector, para saber si se repite el mismo patron con respecto a los distintos rangos de descuento y la ganancia.

Podemos observar que:

*   La categoria de **tecnologia** es la que tiene más variación de ganancia.
*   En las tres categorias hay una perdida de mas del 50% en descuentos muy alto

In [21]:
df["Category"].unique()

array(['Furniture', 'Office Supplies', 'Technology'], dtype=object)

## Estadístico de resumen 2: Profit promedio por rango de descuento

Con el objetivo de analizar la relación entre descuentos y rentabilidad, se calculó la ganancia promedio (**Profit**) para cada rango de descuento definido previamente.

La utilización del profit promedio permite observar cómo varía el resultado económico de las operaciones a medida que aumenta el nivel de descuento aplicado. De esta manera, es posible evaluar si los descuentos contribuyen a mantener la rentabilidad o si, por el contrario, generan una reducción progresiva de las ganancias.

Este análisis constituye uno de los principales indicadores para responder la pregunta de investigación, ya que permite identificar si existe un nivel de descuento a partir del cual las promociones dejan de ser económicamente convenientes para la empresa.

Los resultados obtenidos servirán posteriormente como base para la elaboración de gráficos y para la interpretación de la relación entre descuentos y rentabilidad.

In [22]:
# Profit promedio por rango de descuento

profit_promedio_descuento = (
    df.groupby("Rango_Descuento")["Profit"]
    .mean()
    .round(2)
    .reset_index()
)

# Mostrar tabla de resultados
print(profit_promedio_descuento)

# Mostrar ordenado según los rangos definidos
profit_promedio_descuento

   Rango_Descuento  Profit
0    Sin descuento   66.90
1    Bajo (0%-10%)   96.06
2  Medio (10%-20%)   24.74
3   Alto (20%-40%)  -77.86
4  Muy alto (>40%) -106.71

/tmp/ipykernel_16727/3873323953.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("Rango_Descuento")["Profit"]

   Rango_Descuento  Profit
0    Sin descuento   66.90
1    Bajo (0%-10%)   96.06
2  Medio (10%-20%)   24.74
3   Alto (20%-40%)  -77.86
4  Muy alto (>40%) -106.71

**Interpretación**: El cálculo del profit promedio por rango de descuento permite analizar cómo varía la ganancia obtenida en las operaciones según el nivel de descuento aplicado.

Los resultados muestran una disminución progresiva del profit promedio a medida que aumentan los descuentos, ello sugeriría que las promociones reducen la rentabilidad de las ventas.

## Estadístico de resumen 3: Margen promedio por rango de descuento

Con el objetivo de evaluar cómo afecta el nivel de descuento a la rentabilidad de las operaciones, se calculó el margen de rentabilidad promedio para cada rango de descuento definido previamente.

A diferencia del profit promedio, que muestra la ganancia obtenida en términos absolutos, el margen de rentabilidad permite analizar qué proporción de las ventas se transforma efectivamente en ganancia. Esto facilita la comparación entre operaciones de distinto tamaño y proporciona una medida más precisa de la eficiencia económica de cada grupo.

El análisis del margen promedio resulta especialmente relevante para esta investigación, ya que permite determinar si el aumento de los descuentos reduce la rentabilidad relativa de las ventas y si existe un nivel de descuento a partir del cual dicha rentabilidad comienza a deteriorarse de forma significativa.

Los resultados obtenidos servirán para complementar el análisis de ganancias y aportar evidencia adicional sobre la relación entre descuentos y rentabilidad.

In [23]:
# Resumen estadístico del margen por rango de descuento

resumen_margen = (
    df.groupby("Rango_Descuento")["Margen_Rentabilidad_Porc"]
    .agg(
        Margen_Promedio="mean",
        Margen_Minimo="min",
        Margen_Maximo="max",
        Cantidad_Operaciones="count"
    )
    .round(2)
)

resumen_margen

/tmp/ipykernel_16727/4039059757.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("Rango_Descuento")["Margen_Rentabilidad_Porc"]

,Margen_Promedio,Margen_Minimo,Margen_Maximo,Cantidad_Operaciones
Rango_Descuento,,,,
Sin descuento,34.02,0.00,50.00,4798
Bajo (0%-10%),15.58,-5.56,43.33,94
Medio (10%-20%),17.48,-25.00,37.50,3709
Alto (20%-40%),-16.69,-66.67,27.14,460
Muy alto (>40%),-108.90,-275.00,-2.00,933

**Interpretación:** A medida que aumenta el descuento aplicado, el margen de rentabilidad promedio disminuye de forma sostenida. Los descuentos muy altos presentan márgenes negativos, lo que sugiere que el incremento en las ventas no compensa la reducción de ganancias provocada por la política de descuentos.

###Prompt de IA utilizado para las **transformaciones**:

"Crea el Código para [Especificación del tipo de transformación] el dataframe está guardado con la variable "df". Añade las explicaciones necesarias al código como indica las instrucciones del trabajo practico."

Las especificaciones para cada una fueron:

1.   Crear rangos de descuento. Tipo de transformación: crear columna derivada.
2.   Crear una columna de margen de rentabilidad. Tipo de transformación: crear columna derivada.
3.   Crear una columna que identifique ventas con pérdida. Tipo de transformación: crear columna derivada.

###Prompt de IA utilizado para los **estadísticos agrupados**:

"Crea el Código para el estadistico agrupado [Especificación del tipo de estadistico agrupado] el dataframe está guardado con la variable "df". Añade las explicaciones necesarias al código como indica las instrucciones del trabajo practico"



1.   Profit promedio por categoría y rango de descuento.
Agrupación: Category y Rango_Descuento. Estadístico: promedio de Profit
2.   Profit promedio por rango de descuento.
Agrupación: Rango_Descuento.
Estadístico: promedio de Profit.
3.   Margen promedio por rango de descuento.
Agrupación: Rango_Descuento.
Estadístico: promedio de Margen_Rentabilidad_Porc.

Cada codigo despues fue modificado, realizado una limpieza de errores y adaptado al contenido de la materia.

#**3.4. Análisis gráfico**

Para avanzar con la investigación y validar la hipótesis planteada, en esta sección hay tres visualizaciones complementarias alineadas con las métricas y variables estructuradas. El objetivo principal es ver el impacto de la política de descuentos sobre el beneficio y los márgenes de la organización para hallar el punto de quiebre operativo.

#### Uso de IA y metodología
El diseño estético y la optimización sintáctica del código se realizaron mediante el uso asistido de Inteligencia Artificial.

* **Estrategia y Criterio Analítico:** El uso de la asistencia se limitó estrictamente a emprolijar la estética en Seaborn (paletas de colores legibles, disposición de cuadrículas y líneas de corte), la automatización para exportar los archivos físicos y la mitigación de errores lógicos de ejecución (indeterminaciones matemáticas). La estrategia conceptual, los objetivos y la interpretación económica de los resultados son de autoría humana exclusiva.

* **Prompt de IA utilizado:** > "Actua como un analista de datos senior. Necesito desarrollar el punto 3.4 sobre Análisis gráfico de el Trabajo Práctico de Laboratorio de Métodos Cuantitativos. El análisis debe alinearse con nuestra pregunta de investigación sobre si los descuentos excesivos destruyen la rentabilidad y con las variables creadas en el punto 3.3 (Rango_descuento y Margen_rentabilidad), generá el código de Python utilizando pandas, matplotlib y seaborn para construir tres visualizaciones específicas que cumplan con las consignas: Un histograma con curva de densidad (KDE) para la distribución continua de la variable 'Discount', un gráfico de barras que compare el promedio de 'Profit' según las categorías de 'Rango_descuento', un diagrama de dispersión que relacione la proporción de 'Discount' contra el porcentaje de 'Margen_rentabilidad', incluyendo una línea de corte horizontal en el 0% para identificar pérdidas. Asegurá que el código sea legible, incluyendo np.where para evitar errores de ejecución por división por cero en las operaciones donde las ventas sean iguales a cero. Los gráficos deben tener títulos, etiquetas claras en los ejes y la función plt.savefig para exportarlos automáticamente en formato .png"

#### Justificación de las Visualizaciones Seleccionadas
Cada uno de los gráficos cumple con un rol específico:
1. **Histograma de Distribución:** Analiza la variable continua 'Discount' para evaluar con qué frecuencia y magnitud la empresa recurre a las rebajas en su operación normal.
2. **Gráfico de Barras:** Cruza la variable categórica de rangos de descuento contra la variable numérica 'Profit'. Su fin es contrastar las medias de ganancias y verificar visualmente en qué rango exacto el beneficio cruza el umbral de equilibrio.
3. **Diagrama de Dispersión:** Evalúa la relación directa y continua entre el porcentaje de descuento y el margen operativo neto, identificando patrones y la densidad de transacciones que caen en zona de pérdida.

#### Interpretación de las visualizaciones y cierre Económico

* **Análisis de Distribución:** El histograma revela que la estrategia comercial tiene la mayor densidad de sus transacciones en el nivel de tasa cero (0.0) o rebajas marginales inferiores al 20%. No obstante, se nota un comportamiento constante de transacciones con tasas de descuento notables (superiores al 40% y hasta el 80%).

* **Análisis de Comparación Categórica:** El gráfico de barras confirma la hipótesis planteada. Los estímulos comerciales moderados (Rango Bajo, de 0% a 10%) optimizan la ganancia promedio, superando incluso el rendimiento de las operaciones sin descuento. Sin embargo, al alcanzar el rango "Alto" (20% a 40%), el beneficio medio quiebra la barrera del cero y entra en el lugar de pérdida operativa, profundizándose de manera drástica en el nivel "Muy Alto".

* **Análisis de relación entre Variables:** El diagrama de dispersión muestra detalladamente la sensibilidad marginal de la rentabilidad. Existe una correlación negativa entre el incremento del descuento y el margen operativo porcentual. El hallazgo más crítico nos dice que, una vez superada la proporción de 0.2 (20% de descuento), la dispersión de puntos queda casi en su totalidad por debajo de la línea roja de equilibrio (0%).

**Conclusión del Impacto en el Negocio (Punto de Quiebre):**
Los tres análisis gráficos validan la hipótesis de investigación. Mientras que las rebajas leves (menores al 10%) impulsa el negocio, **el umbral del 20% representa el punto de quiebre para la organización**. Pasar este límite no genera ventajas competitivas por volumen, sino que desploma el margen operativo unitario, provocando pérdidas sistemáticas. Los datos sugieren que la gerencia debería establecer una restricción en los sistemas comerciales que bloquee automáticamente cualquier descuento mayor al 20% para proteger financieramente la empresa.

#**3.5. Aplicación de conceptos de la materia**